# Generated by Django 4.1.1 on 2022-09-15 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=50)),
                ('officer_department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_id', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('offence', models.CharField(max_length=64)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=50, null=True)),
                ('officer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PenaltyManager.officer')),
            ],
        ),
    ]
