# Generated by Django 4.1.1 on 2022-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PenaltyManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
