# Generated by Django 4.1 on 2022-09-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PenaltyManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='vehicle_regno',
            new_name='vehicle_plate',
        ),
    ]
