# Generated by Django 4.1 on 2022-09-07 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PenaltyManager', '0002_rename_vehicle_regno_driver_vehicle_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_name',
            new_name='driver_firstname',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
